### ISSUE TITLE
Организация задержки в начале работы

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/Robofest2018#3]
Может организовать работу задержки в начале с использование функций ядра `chThdSleep*`? Тогда таймер останется свободным

**Comment by serykhelena** [comment]
Т.е. просто вместо функции -  gptPolledDelay( &GPTD3, 50000 ); использовать chThdSleep* в том же самом цикле?

**Comment by KaiL4eK** [comment]
Там есть chThdSleepSeconds() функция, можно попробовать использовать ее
